// flow-typed signature: f81d8d7d9092a0a8d673cd7f0488fb18
// flow-typed version: <<STUB>>/redux-mock-store-await-actions_v2.1.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-mock-store-await-actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-mock-store-await-actions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-mock-store-await-actions/test/index.spec' {
  declare module.exports: any;
}

declare module 'redux-mock-store-await-actions/test/util/assertError' {
  declare module.exports: any;
}

declare module 'redux-mock-store-await-actions/test/util/index' {
  declare module.exports: any;
}

declare module 'redux-mock-store-await-actions/test/util/spyOnThrottleCancel' {
  declare module.exports: any;
}

declare module 'redux-mock-store-await-actions/test/util/spyOnUnsubscribe' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-mock-store-await-actions/index' {
  declare module.exports: $Exports<'redux-mock-store-await-actions'>;
}
declare module 'redux-mock-store-await-actions/index.js' {
  declare module.exports: $Exports<'redux-mock-store-await-actions'>;
}
declare module 'redux-mock-store-await-actions/test/index.spec.js' {
  declare module.exports: $Exports<'redux-mock-store-await-actions/test/index.spec'>;
}
declare module 'redux-mock-store-await-actions/test/util/assertError.js' {
  declare module.exports: $Exports<'redux-mock-store-await-actions/test/util/assertError'>;
}
declare module 'redux-mock-store-await-actions/test/util/index.js' {
  declare module.exports: $Exports<'redux-mock-store-await-actions/test/util/index'>;
}
declare module 'redux-mock-store-await-actions/test/util/spyOnThrottleCancel.js' {
  declare module.exports: $Exports<'redux-mock-store-await-actions/test/util/spyOnThrottleCancel'>;
}
declare module 'redux-mock-store-await-actions/test/util/spyOnUnsubscribe.js' {
  declare module.exports: $Exports<'redux-mock-store-await-actions/test/util/spyOnUnsubscribe'>;
}
