export const REGISTER_COMPANY_REQUEST = 'REGISTER_COMPANY_REQUEST';
export const REGISTER_COMPANY_SUCCESS = 'REGISTER_COMPANY_SUCCESS';
export const REGISTER_COMPANY_FAILURE = 'REGISTER_COMPANY_FAILURE';

export const REGISTER_FREELANCER_REQUEST = 'REGISTER_FREELANCER_REQUEST';
export const REGISTER_FREELANCER_SUCCESS = 'REGISTER_FREELANCER_SUCCESS';
export const REGISTER_FREELANCER_FAILURE = 'REGISTER_FREELANCER_FAILURE';
